account_app/urls.py
from django.urls import path
from .views import (
    Register, Login, logout_view, add_course_to_cart, CartView, delete_course_from_cart, MyCourses,
    PasswordChange, CourseAdd, TeacherCourses, MyComment, TeacherBlogs, PaymentList, PaymentDetail, BlogCreate,VideoAdd,VideoUpdate
    ,PasswordReset,PasswordResetConfirm,ProfileUpdate,BlogUpdate,CourseUpdate,VideoList,checkout,apply_coupon_code,remove_coupon_code
)

app_name = 'account'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('apply-coupon-code/', apply_coupon_code, name='apply_coupon_code'),
    path('remove-coupon-code/', remove_coupon_code, name='remove_coupon_code'),
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password_change'),
    path('profile/', ProfileUpdate.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
    path('my-courses/', MyCourses.as_view(), name='my_courses'),
    path('add-courses-to-order/<int:pk>/', add_course_to_cart, name='add_course_to_cart'),
    path('delete-courses-from-order/<int:pk>/', delete_course_from_cart, name='delete_course_to_cart'),
    path('course-add/', CourseAdd.as_view(), name='course_add'),
    path('course-update/<int:pk>/', CourseUpdate.as_view(), name='course_update'),
    path('teacher-videos-courses/', VideoList.as_view(), name='teacher_videos'),
    path('video-course-add/', VideoAdd.as_view(), name='video_course_add'),
    path('video-course-update/<int:pk>/', VideoUpdate.as_view(), name='video_course_update'),
    path('teacher-courses/', TeacherCourses.as_view(), name='teacher_courses'),
    path('my-comment/', MyComment.as_view(), name='my_comment'),
    path('teacher-blogs/', TeacherBlogs.as_view(), name='teacher_blogs'),
    path('blog-create/', BlogCreate.as_view(), name='blog_create'),
    path('blog-update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('payments/', PaymentList.as_view(), name='payment_list'),
    path('payments/<int:pk>/', PaymentDetail.as_view(), name='payment_detail'),
    path('password-reset/',PasswordReset.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
]

blog_app/urls.py
from django.urls import path
from .views import BlogList, BlogDetail

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogList.as_view(), name='blog_list'),
    path('blog/<int:pk>/<slug>/', BlogDetail.as_view(), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload
from azbankgateways.urls import az_bank_gateways_urls
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('index_app.urls', namespace='index')),
    path('', include('course_app.urls', namespace='course')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('order_app.urls', namespace='order')),
    path('', include('blog_app.urls', namespace='blog')),
    path('contact/', include('contact_app.urls', namespace='contact')),
    path('account/', include('account_app.urls', namespace='account')),
    path('about-us/',include('about_app.urls',namespace='about_us')),
    path('editor/uploads/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/login/', RedirectView.as_view(url='/account/login/')),
    path('admin/', admin.site.urls),
]

handler404 = 'config.views.view_404'
handler403 = 'config.views.view_403'
handler400 = 'config.views.view_400'
handler500 = 'config.views.view_500'

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

course_app/urls.py
from django.urls import path
from .views import CourseList, CourseDetail

app_name = 'course'

urlpatterns = [
    path('courses/', CourseList.as_view(), name='course_list'),
    path('courses/<int:pk>/<slug>/', CourseDetail.as_view(), name='course_detail'),
]

templates/index/index.html
{% extends 'Shared/Base.html' %}
{% load humanize %}
{% load static %}
{% block head_title %}صفحه اصلی{% endblock %}
{% block content %}
    <!-- Main Slider -->
    <div class="section-area section-sp1 ovpr-dark bg-fix online-cours"
         style="background-image:url({% static 'images/background/bg1.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center text-white">
                    <h2>دوره‌های آنلاین آموزشی</h2>
                    <h5>آینده را با یادگرفتن مهارت‌ به کام خود کنید</h5>
                    <form method="get" class="cours-search" action="{% url 'course:course_list' %}">
                        <div class="input-group">
                            <input name="search" type="text" class="form-control"
                                   placeholder="دنبال چه دوره ای میگردی؟" required>
                            <div class="input-group-append">
                                <button class="btn" type="submit">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Slider -->
    <div class="content-block">
        <!-- Last Courses -->
        <div class="section-area section-sp2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 heading-bx left">
                        <h2 class="title-head">آخرین <span>دوره‌ها</span></h2>
                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                            است.</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="row">
                        {% for course in last_courses %}
                            <div class="col-md-6 col-lg-6 col-xl-3 col-sm-6 m-b30">
                                <div class="cours-bx">
                                    <div class="action-box">
                                        <a href="{{ course.course_url }}"><img src="{{ course.image.url }}"
                                                                               alt="{{ course.title }}"></a>
                                        <a href="{{ course.course_url }}"
                                           class="btn">بیشتر بخوانید</a>
                                    </div>
                                    <div class="info-bx text-center">
                                        <h5><a style="font-size: 15px"
                                               href="{{ course.course_url }}">{{ course.title|truncatechars:29 }}</a>
                                        </h5>
                                        <span>{{ course.category_to_str }}</span>
                                    </div>
                                    <div class="cours-more-info">
                                        <div class="price">
                                            {% if course.price == 0 %}
                                                <h5>
                                                    <span style="color: #018f23">رایگان !</span>
                                                </h5>
                                            {% elif course.discount == 100 %}
                                                <h5>
                                                    <del style="color:#ff3f3f;">{{ course.price | intcomma:False }}</del>
                                                    <span style="color: #018f23">رایگان !</span>
                                                </h5>
                                            {% elif course.discount < 100 %}
                                                <h5>
                                                    <del style="color:#ff3f3f;">{{ course.price | intcomma:False }}</del>
                                                    {{ course.total_price | intcomma:False }} تومان
                                                </h5>
                                            {% else %}
                                                <h5> {{ course.total_price | intcomma:False }} تومان </h5>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Last Courses END -->

        <div class="section-area section-sp2 bg-fix ovbl-dark join-bx text-center"
             style="background-image:url({% static 'images/background/bg1.jpg' %});">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="join-content-bx text-white">
                            <h2>مهارت جدیدی را <br>آنلاین بیاموزید</h2>
                            <h4><span class="counter">{{ courses_count|intcomma:False }}</span> دوره آنلاین </h4>
                            <p> نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو
                                در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه
                                راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و
                                جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'course:course_list' %}" class="btn button-md btn-block">دوره ها</a>
                            {% else %}
                                <a href="{% url 'account:register' %}" class="btn button-md btn-block">ثبت نام کنید</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Form END -->
        <!-- Popular Courses -->
        <div class="section-area section-sp2 popular-courses-bx">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 heading-bx left">
                        <h2 class="title-head">محبوب‌ترین <span>دوره‌ها</span></h2>
                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                            است.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="courses-carousel owl-carousel owl-btn-1 col-12 p-lr0">
                        {% for course in popular_courses %}
                            <div class="item">
                                <div class="cours-bx">
                                    <div class="action-box">
                                        <a href="{{ course.course_url }}"><img src="{{ course.image.url }}"
                                                                               alt="{{ course.title }}"></a>
                                        <a href="{{ course.course_url }}"
                                           class="btn">بیشتر بخوانید</a>
                                    </div>
                                    <div class="info-bx text-center">
                                        <h5><a style="font-size: 15px"
                                               href="{{ course.course_url }}">{{ course.title|truncatechars:29 }}</a>
                                        </h5>
                                        <span>{{ course.category_to_str }}</span>
                                    </div>
                                    <div class="cours-more-info">
                                        <div class="price">
                                            {% if course.price == 0 %}
                                                <h5>
                                                    <span style="color: #018f23">رایگان !</span>
                                                </h5>
                                            {% elif course.discount == 100 %}
                                                <h5>
                                                    <del style="color:#ff3f3f;">{{ course.price | intcomma:False }}</del>
                                                    <span style="color: #018f23">رایگان !</span>
                                                </h5>
                                            {% elif course.discount < 100 %}
                                                <h5>
                                                    <del style="color:#ff3f3f;">{{ course.price | intcomma:False }}</del>
                                                    {{ course.total_price | intcomma:False }} تومان
                                                </h5>
                                            {% else %}
                                                <h5> {{ course.total_price | intcomma:False }} تومان </h5>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Popular Courses END -->
        <!-- Testimonials -->
        <div class="section-area section-sp1 bg-fix ovbl-dark text-white"
             style="background-image:url({% static 'images/background/bg1.jpg' %});">
            <div class="container">
                <div class="row text-center">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-12 m-b30">
                        <div class="counter-style-1">
                            <div class="text-white">
                                <span class="counter">{{ courses_count|intcomma:False }}</span><span>+</span>
                            </div>
                            <span class="counter-text">دوره</span>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-12 m-b30">
                        <div class="counter-style-1">
                            <div class="text-white">
                                <span class="counter">{{ students_count|intcomma:False }}</span><span>+</span>
                            </div>
                            <span class="counter-text">دانشجو</span>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-12 m-b30">
                        <div class="counter-style-1">
                            <div class="text-white">
                                <span class="counter">{{ teachers_count|intcomma:False }}</span><span>+</span>
                            </div>
                            <span class="counter-text">مدرس</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Testimonials END -->
        <!-- RECENT BLOG ==== -->
        <div class="section-area section-sp2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 heading-bx left">
                        <h2 class="title-head">آخرین <span> مقالات</span></h2>
                    </div>
                </div>
                <div class="ttr-blog-grid-3 row" id="masonry" style="position: relative; height: 1676.11px;">
                    {% for blog in last_blogs %}
                        <div class="post action-card col-lg-4 col-md-6 col-sm-12 col-xs-12 m-b40"
                             style="position: absolute; right: 0px; top: 0px;">
                            <div class="recent-news">
                                <div class="action-box">
                                    <a href="{% url 'blog:blog_detail' blog.pk blog.slug %}"><img
                                            src="{{ blog.image.url }}" alt="{{ blog.title }}"></a>
                                </div>
                                <div class="info-bx">
                                    <ul class="media-post">
                                        <li><a><i class="fa fa-calendar"></i>{{ blog.get_jalali_date_for_url }}
                                        </a></li>
                                        <li><a href="#"><i class="fa fa-user"></i>{{ blog.get_author_name }}</a></li>
                                    </ul>
                                    <h5 class="post-title"><a
                                            href="{% url 'blog:blog_detail' blog.pk blog.slug %}">{{ blog.title }}</a>
                                    </h5>
                                    <p class="text-center">{{ blog.description|striptags|safe|truncatechars:100 }}</p>
                                    <div class="post-extra">
                                        <a href="{% url 'blog:blog_detail' blog.pk blog.slug %}" class="btn-link">بیشتر
                                            بخوانید</a>
                                        <a class="comments-bx"><i
                                                class="fa fa-comments-o"></i>{{ blog.comments.get_active_comment.count }}
                                            دیدگاه</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- RECENT BLOG END ==== -->
        </div>
        <!-- contact area END -->
{% endblock %}