account_app/urls.py
from django.urls import path
from .views import (
    Register, Login, logout_view, add_course_to_cart, CartView, delete_course_from_cart, MyCourses,
    PasswordChange, CourseAdd, TeacherCourses, MyComment, TeacherBlogs, PaymentList, PaymentDetail, BlogCreate,VideoAdd,VideoUpdate
    ,PasswordReset,PasswordResetConfirm,ProfileUpdate,BlogUpdate,CourseUpdate,VideoList,checkout,apply_coupon_code,remove_coupon_code
)

app_name = 'account'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('apply-coupon-code/', apply_coupon_code, name='apply_coupon_code'),
    path('remove-coupon-code/', remove_coupon_code, name='remove_coupon_code'),
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password_change'),
    path('profile/', ProfileUpdate.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
    path('my-courses/', MyCourses.as_view(), name='my_courses'),
    path('add-courses-to-order/<int:pk>/', add_course_to_cart, name='add_course_to_cart'),
    path('delete-courses-from-order/<int:pk>/', delete_course_from_cart, name='delete_course_to_cart'),
    path('course-add/', CourseAdd.as_view(), name='course_add'),
    path('course-update/<int:pk>/', CourseUpdate.as_view(), name='course_update'),
    path('teacher-videos-courses/', VideoList.as_view(), name='teacher_videos'),
    path('video-course-add/', VideoAdd.as_view(), name='video_course_add'),
    path('video-course-update/<int:pk>/', VideoUpdate.as_view(), name='video_course_update'),
    path('teacher-courses/', TeacherCourses.as_view(), name='teacher_courses'),
    path('my-comment/', MyComment.as_view(), name='my_comment'),
    path('teacher-blogs/', TeacherBlogs.as_view(), name='teacher_blogs'),
    path('blog-create/', BlogCreate.as_view(), name='blog_create'),
    path('blog-update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('payments/', PaymentList.as_view(), name='payment_list'),
    path('payments/<int:pk>/', PaymentDetail.as_view(), name='payment_detail'),
    path('password-reset/',PasswordReset.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
]

blog_app/urls.py
from django.urls import path
from .views import BlogList, BlogDetail

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogList.as_view(), name='blog_list'),
    path('blog/<int:pk>/<slug>/', BlogDetail.as_view(), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload
from azbankgateways.urls import az_bank_gateways_urls
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('index_app.urls', namespace='index')),
    path('', include('course_app.urls', namespace='course')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('order_app.urls', namespace='order')),
    path('', include('blog_app.urls', namespace='blog')),
    path('contact/', include('contact_app.urls', namespace='contact')),
    path('account/', include('account_app.urls', namespace='account')),
    path('about-us/',include('about_app.urls',namespace='about_us')),
    path('editor/uploads/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/login/', RedirectView.as_view(url='/account/login/')),
    path('admin/', admin.site.urls),
]

handler404 = 'config.views.view_404'
handler403 = 'config.views.view_403'
handler400 = 'config.views.view_400'
handler500 = 'config.views.view_500'

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

index_app/urls.py
from django.urls import path
from .views import index_page

app_name = 'index'

urlpatterns = [
    path('', index_page, name='index_page')
]

templates/blog/blog-detail.html
{% extends 'Shared/Base.html' %}
{% load render_partial %}
{% load widget_tweaks %}
{% load static %}
{% block head_title %}مقاله {{ object.title }}{% endblock %}
{% block content %}
    <!-- inner page banner -->
    <div class="page-banner ovbl-dark" style="background-image:url({{ object.image.url }});">
        <div class="container">
            <div class="page-banner-entry">
                <h1 class="text-white">مقاله {{ object.title }}</h1>
            </div>
        </div>
    </div>
    <!-- Breadcrumb row -->
    <div class="breadcrumb-row">
        <div class="container">
            <ul class="list-inline">
                <li><a href="{% url 'index:index_page' %}">خانه</a></li>
                <li><a href="{% url 'blog:blog_list' %}">مقالات</a></li>
                <li><a href="{% url 'blog:blog_detail' object.pk object.slug %}">{{ object.title }}</a></li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb row END -->
    <div class="content-block">
        <div class="section-area section-sp1">
            <div class="container">
                <div class="row">
                    <!-- Left part start -->
                    <div class="col-lg-8 col-xl-8">
                        <!-- blog start -->
                        <div class="recent-news blog-lg">
                            <div class="action-box blog-lg">
                                <img src="{{ object.image.url }}" alt="{{ object.title }}">
                            </div>
                            <div class="info-bx">
                                <ul class="media-post">
                                    <li><a><i class="fa fa-user"></i>{{ object.get_author_name }}
                                    </a></li>
                                    <li><a><i class="fa fa-calendar"></i>{{ object.get_jalali_date_for_url }}
                                    </a></li>
                                    <li><a><i
                                            class="fa fa-comments-o"></i>{{ object.comments.get_active_comment.count }}
                                        دیدگاه</a></li>
                                    <li><a><i
                                            class="fa fa-eye"></i>{{ object.hits.all.count }} بازدید</a></li>
                                </ul>
                                <h5 class="post-title"><a href="#">{{ object.title }}</a></h5>
                                {{ object.description|safe }}
                                <div class="ttr-divider bg-gray"><i class="icon-dot c-square"></i></div>
                                <div class="widget_tag_cloud">
                                    <h6>برچسب ها</h6>
                                    <div class="tagcloud">
                                        {% for tag in object.tags.get_active_tag %}
                                            <a href="{% url 'blog:blog_list' %}?search={{ tag.title }}">{{ tag.title }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="ttr-divider bg-gray"><i class="icon-dot c-square"></i></div>
                                <h6>اشتراک</h6>
                                <ul class="list-inline contact-social-bx">
                                    <li><a target="_blank" href="whatsapp://send?text=http://127.0.0.1:8000{% url 'blog:blog_detail' object.pk object.slug %}" class="btn outline radius-xl"><i class="fa fa-whatsapp"></i></a>
                                    </li>
                                    <li><a target="_blank" href="https://twitter.com/share?url=http://127.0.0.1:8000{% url 'blog:blog_detail' object.pk object.slug %}" class="btn outline radius-xl"><i class="fa fa-twitter"></i></a></li>
                                    <li><a target="_blank" href="https://t.me/share/url?url=http://127.0.0.1:8000{% url 'blog:blog_detail' object.pk object.slug %}" class="btn outline radius-xl"><i class="fa fa-telegram"></i></a>
                                    </li>
                                    <li><a target="_blank" href="http://www.facebook.com/sharer.php?u=http://127.0.0.1:8000{% url 'blog:blog_detail' object.pk object.slug %}" class="btn outline radius-xl"><i class="fa fa-facebook"></i></a>
                                    </li>
                                    <li><a target="_blank" href="mailto:?subject={{ object.title }}&body=http://127.0.0.1:8000{% url 'blog:blog_detail' object.pk object.slug %}" class="btn outline radius-xl"><i class="fa fa-envelope"></i></a>
                                    </li>
                                </ul>
                                <div class="ttr-divider bg-gray"><i class="icon-dot c-square"></i></div>
                            </div>
                        </div>
                        <div class="clear" id="comment-list">
                            <div class="comments-area" id="comments">
                                <div class="clearfix m-b20">
                                    <!-- Form -->
                                    <div class="comment-respond mb-3" id="respond">
                                        <h4 class="comment-reply-title" id="reply-title">دیدگاه خود را بنویسید<small>
                                        </small></h4>
                                        <div id="review">
                                            {% if user.is_authenticated %}
                                                <form class="comment-form" id="commentform" method="post">
                                                    {% csrf_token %}
                                                    {{ form.recaptcha }} 
                                                    <p class="comment-form-comment">
                                                        <label for="comment">دیدگاه</label>
                                                        {% render_field form.message rows="8" placeholder="دیدگاه" id="comment" %}
                                                    </p>
                                                    <input type="hidden" value id="parent_id" name="parent_id" >
                                                    <p class="form-submit">
                                                        <input type="submit" value="ثبت دیدگاه" class="submit"
                                                               id="submit"
                                                               name="submit">
                                                    </p>
                                                </form>
                                            {% else %}
                                                <p class="alert alert-warning text-center">برای ثبت دیدگاه باید <a
                                                        href="{% url 'account:login' %}?next={{ request.get_full_path }}">وارد</a>
                                                    شوید.</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    {% if form.message.errors %}
                                            {% for error in form.message.errors %}
                                                <div class="col-12 mt-3" >
                                                    <p class="alert alert-danger text-center">
                                                        {{ error }}
                                                    </p>    
                                                </div>
                                            {% endfor %}
                                    {% endif %}
                                    {% if object.comments.get_active_comment %}
                                        <h2 class="comments-title">{{ object.comments.get_active_comment.count }}
                                            دیدگاه</h2>
                                    {% else %}
                                        <div class="col-lg-12">
                                            <p class="alert alert-success text-center">شما اولین دیدگاه را ثبت کنید</p>
                                        </div>
                                    {% endif %}
                                    <!-- Form -->
                                    <!-- comment list END -->
                                    {% if object.comments.get_active_comment %}
                                        <ol class="comment-list">
                                            <li class="comment">
                                                {% for comment in object.comments.get_active_comment %}
                                                    <div class="comment-body {% if comment.user == object.teacher %}teacher-comment{% endif %}">
                                                        <div class="comment-author vcard"><img class="avatar photo"
                                                                                            src="{{ comment.user.profile.get_avatar }}"
                                                                                            alt="{{ comment.get_user_name }}">
                                                            <cite
                                                                    class="fn">{{ comment.get_user_name }}</cite>
                                                            <span class="says">نوشته:</span></div>
                                                        <div class="comment-meta"><a>{{ comment.jalali_time }}</a>
                                                        </div>
                                                        <p class="text-justify">{{ comment.message }}</p>
                                                        <div class="reply"><a href="#comments" onclick="updateParentInput({{comment.id}})">پاسخ</a>
                                                        </div>
                                                        <div class="replies mt-3">
                                                            {% for reply in comment.replies.get_active_reply %}
                                                                <ol class="children">
                                                                    <li class="comment odd parent">
                                                                        <div class="comment-body {% if reply.user == object.teacher %}teacher-comment{% endif %}">
                                                                            <div class="comment-author vcard"><img
                                                                                    class="avatar photo"
                                                                                    src="{{ reply.user.profile.get_avatar }}"
                                                                                    alt="{{ reply.get_user_name }}"> <cite
                                                                                    class="fn">{{ reply.get_user_name }}</cite>
                                                                                <span class="says">نوشته:</span></div>
                                                                            <div class="comment-meta">
                                                                                <a>{{ reply.jalali_time }}</a>
                                                                            </div>
                                                                            <p class="text-justify pl-2">{{ reply.message }}</p>
                                                                        </div>
                                                                        <!-- list END -->
                                                                    </li>
                                                                </ol>
                                                            {% endfor %}
                                                        </div>


                                                    </div>
                                                {% endfor %}

                                                <!-- list END -->
                                            </li>
                                        </ol>
                                    {% endif %}
                                    <!-- comment list END -->
                                </div>
                            </div>
                        </div>
                        <!-- blog END -->
                    </div>
                    <!-- Left part END -->
                    <!-- Side bar start -->
                    {% render_partial 'blog_app.views.sidebar_blog' %}
                    <!-- Side bar END -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block add_footer_reference %}
    <script>
    function updateParentInput(num){
        document.getElementById("parent_id").value = num;
        $("#reply-title").text("پاسخ خود را بنویسید");
    }
    </script>
{% endblock %}

templates/blog/blog-list.html
{% extends 'Shared/Base.html' %}
{% load render_partial %}
{% load static %}
{% block head_title %}مقالات {% if request.GET.search %}جستجوی
    {{ request.GET.search }}
{% endif %}{% endblock %}
{% block content %}
    <!-- inner page banner -->
    <div class="page-banner ovbl-dark" style="background-image:url({% static 'images/banner/banner2.jpg' %});">
        <div class="container">
            <div class="page-banner-entry">
                <h1 class="text-white">{% if request.GET.search %}مقالات | جستجوی {{ request.GET.search }}{% else %}
                    مقالات{% endif %}</h1>
            </div>
        </div>
    </div>
    <!-- Breadcrumb row -->
    <div class="breadcrumb-row">
        <div class="container">
            <ul class="list-inline">
                <li><a href="{% url 'index:index_page' %}">خانه</a></li>
                <li><a href="{% url 'blog:blog_list' %}">مقالات</a></li>
                {% if request.GET.search %}
                    <li>
                        <a>جستجوی {{ request.GET.search }}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!-- Breadcrumb row END -->
    <!-- contact area -->
    <div class="content-block">
        <div class="section-area section-sp1">
            <div class="container">
                <div class="row">
                    <!-- Left part start -->
                    <div class="col-lg-8">
                        {% if page_obj %}
                            {% for blog in page_obj %}
                                <div class="blog-post blog-md clearfix">
                                    <div class="ttr-post-media">
                                        <a href="{% url 'blog:blog_detail' blog.pk blog.slug %}"><img
                                                src="{{ blog.image.url }}" alt="{{ blog.title }}"></a>
                                    </div>
                                    <div class="ttr-post-info">
                                        <ul class="media-post">
                                            <li><a><i class="fa fa-calendar"></i>{{ blog.get_jalali_date_for_url }}</a>
                                            </li>
                                            <li><a href="#"><i class="fa fa-user"></i>{{ blog.get_author_name }}</a>
                                            </li>
                                        </ul>
                                        <h5 class="post-title"><a
                                                href="{% url 'blog:blog_detail' blog.pk blog.slug %}">{{ blog.title }}</a>
                                        </h5>
                                        <p class="text-justify">{{ blog.description|striptags|safe|truncatechars:100 }}</p>

                                        <div class="post-extra">
                                            <a href="{% url 'blog:blog_detail' blog.pk blog.slug %}" class="btn-link">بیشتر
                                                بخوانید</a>
                                            <a class="comments-bx"><i
                                                    class="fa fa-comments-o"></i>{{ blog.comments.get_active_comment.count }}
                                                دیدگاه</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <!-- Pagination start -->
                            {% if page_obj.paginator.num_pages != 1 %}
                                <div class="pagination-bx rounded-sm gray clearfix">
                                    <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                            <li class="previous"><a
                                                    href="?page={{ page_obj.previous_page_number }}"><i
                                                    class="ti-arrow-right"></i> قبلی</a>
                                            </li>
                                        {% endif %}
                                        {% if page_obj.number|add:-2 <= page_obj.paginator.num_pages and page_obj.number|add:-2 >= 1 %}
                                            <li>
                                                <a href="?page={{ page_obj.number|add:-2 }}">{{ page_obj.number|add:-2 }}</a>
                                            </li>
                                        {% endif %}
                                        {% if page_obj.has_previous %}
                                            <li>
                                                <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                                            </li>
                                        {% endif %}
                                        <li class="active"><a
                                                href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                                        </li>
                                        {% if page_obj.has_next %}
                                            <li>
                                                <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                                            </li>
                                        {% endif %}
                                        {% if page_obj.number|add:2 <= page_obj.paginator.num_pages %}
                                            <li>
                                                <a href="?page={{ page_obj.number|add:2 }}">{{ page_obj.number|add:2 }}</a>
                                            </li>
                                        {% endif %}
                                        {% if page_obj.has_next %}
                                            <li class="next"><a href="?page={{ page_obj.next_page_number }}">بعدی<i
                                                    class="ti-arrow-left"></i></a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            {% endif %}
                            <!-- Pagination END -->
                        {% else %}
                            <div class="col-lg-12">
                                <p class="alert alert-warning text-center">مقاله ای یافت نشد</p>
                            </div>
                        {% endif %}
                    </div>
                    <!-- Left part END -->
                    <!-- Side bar start -->
                    {% render_partial 'blog_app.views.sidebar_blog' %}
                    <!-- Side bar END -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/sidebar-blog.html
{% load widget_tweaks %}
<div class="col-lg-4 sticky-top">
    <aside class="side-bar sticky-top">
        <div class="widget">
            <h6 class="widget-title">جستجو</h6>
            <div class="search-bx style-1">
                <form role="search" method="get" action="{% url 'blog:blog_list' %}">
                    <div class="input-group">
                        <input name="search" class="form-control" placeholder="جستجو کنید"
                               type="text">
                        <span class="input-group-btn"><button type="submit" class="fa fa-search text-primary"></button></span>
                    </div>
                </form>
            </div>
        </div>
        <div class="widget recent-posts-entry">
            <h6 class="widget-title">آخرین مقالات</h6>
            <div class="widget-post-bx">
                {% for blog in blogs %}
                    <div class="widget-post clearfix">
                        <div class="ttr-post-media"><a href="{% url 'blog:blog_detail' blog.pk blog.slug %}"><img
                                src="{{ blog.image.url }}"
                                width="200" height="143" alt="{{ blog.title }}"></a></div>
                        <div class="ttr-post-info">
                            <div class="ttr-post-header">
                                <h6 class="post-title"><a
                                        href="{% url 'blog:blog_detail' blog.pk blog.slug %}">{{ blog.title }}</a></h6>
                            </div>
                            <ul class="media-post">
                                <li><a href="#"><i class="fa fa-calendar"></i>{{ blog.get_jalali_date_for_url }}</a>
                                </li>
                                <li><a href="#"><i
                                        class="fa fa-comments-o"></i>{{ blog.comments.get_active_comment.count }} دیدگاه</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="widget widget_tag_cloud">
            <h6 class="widget-title">آخرین برچسب ها</h6>
            <div class="tagcloud">
                {% for tag in tags %}
                    <a href="{% url 'blog:blog_list' %}?search={{ tag.title }}">{{ tag.title }}</a>
                {% endfor %}
            </div>
        </div>
    </aside>
</div>