about_app/urls.py
from django.urls import path
from .views import about_us

app_name = 'about_us'

urlpatterns = [
    path('',about_us,name='about_us')
]

blog_app/urls.py
from django.urls import path
from .views import BlogList, BlogDetail

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogList.as_view(), name='blog_list'),
    path('blog/<int:pk>/<slug>/', BlogDetail.as_view(), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload
from azbankgateways.urls import az_bank_gateways_urls
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('index_app.urls', namespace='index')),
    path('', include('course_app.urls', namespace='course')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('order_app.urls', namespace='order')),
    path('', include('blog_app.urls', namespace='blog')),
    path('contact/', include('contact_app.urls', namespace='contact')),
    path('account/', include('account_app.urls', namespace='account')),
    path('about-us/',include('about_app.urls',namespace='about_us')),
    path('editor/uploads/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/login/', RedirectView.as_view(url='/account/login/')),
    path('admin/', admin.site.urls),
]

handler404 = 'config.views.view_404'
handler403 = 'config.views.view_403'
handler400 = 'config.views.view_400'
handler500 = 'config.views.view_500'

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

course_app/urls.py
from django.urls import path
from .views import CourseList, CourseDetail

app_name = 'course'

urlpatterns = [
    path('courses/', CourseList.as_view(), name='course_list'),
    path('courses/<int:pk>/<slug>/', CourseDetail.as_view(), name='course_detail'),
]

index_app/urls.py
from django.urls import path
from .views import index_page

app_name = 'index'

urlpatterns = [
    path('', index_page, name='index_page')
]

templates/Shared/Base.html
{% load base_tags %}
{% load render_partial %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <!-- PAGE TITLE HERE ============================================= -->
    <title>{% block head_title %}{% endblock %} | {% site_title %}</title>
    {% render_partial 'index_app.views.header_references' %}
    {% block add_header_reference %}{% endblock %}
</head>

<body id="bg">
<div class="page-wraper">
    <div id="loading-icon-bx"></div>
    <!-- Header Top ==== -->
    {% render_partial 'index_app.views.site_header' %}
    <!-- header END ==== -->
    <!-- Content -->
    <div class="page-content bg-white">
        {% block content %}{% endblock %}
    </div>
    <!-- Content END-->
    <!-- Footer ==== -->
    {% render_partial 'index_app.views.footer' %}
    <!-- Footer END ==== -->
    <button class="back-to-top fa fa-chevron-up"></button>
</div>
{% include 'Shared/_FooterReferences.html' %}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% if messages %}
    {% for m in messages %}
        <script>
        {% if "success" in m.tags %}
            swal({title:"ایجوکمپ",text:"{{ m }}",icon:"success",  confirmButtonText: 'باشه'
            })
        {% elif "error" in m.tags %}
            swal({title:"ایجوکمپ",text:"{{ m }}",icon:"error",  confirmButtonText: 'باشه'
            })
        {% else %}
            swal({title:"ایجوکمپ",text:"{{ m }}",icon:"info",  confirmButtonText: 'باشه'
            })
        {% endif %}
        </script>
    {% endfor %}
{% endif %} 
{% block add_footer_reference %}{% endblock %}
</body>


</html>

templates/Shared/Footer.html
{% load static %}
<footer>
    <div class="footer-top">
        <div class="pt-exebar">
            <div class="container">
                <div class="d-flex align-items-stretch">
                    <div class="pt-logo mr-auto">
                        <a href="{% url 'index:index_page' %}"><img src="{% static 'images/logo-white.png' %}" alt=""/></a>
                    </div>
                    <div class="pt-social-link">
                        <ul class="list-inline m-a0">
                            {% if youtube %}
                                <li><a target="_blank" href="{{ youtube }}" class="btn-link"><i
                                        class="fa fa-youtube-play"></i></a></li>
                            {% endif %}
                            {% if twitter %}
                                <li><a target="_blank" href="https://twitter.com/{{ twitter }}" class="btn-link"><i
                                        class="fa fa-twitter"></i></a></li>
                            {% endif %}
                            {% if instagram %}
                                <li><a target="_blank" href="https://www.instagram.com/{{ instagram }}" class="btn-link"><i
                                        class="fa fa-instagram"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="pt-btn-join">
                        {% if user.is_authenticated %}
                            <a href="{% url 'course:course_list' %}" class="btn ">دوره ها</a>
                        {% else %}
                            <a href="{% url 'account:register' %}" class="btn ">عضو شوید</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12 footer-col-4">
                    <div class="widget">
                        <h5 class="footer-title">جستجوی دوره ها</h5>
                        <p class="text-capitalize m-b20">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
                            استفاده از طراحان گرافیک است.</p>
                        <div class="subscribe-form m-b20">
                            <form class="subscription-form"
                                  action="{% url 'course:course_list' %}" method="get">
                                <div class="ajax-message"></div>
                                <div class="input-group">
                                    <input name="search" required="required" class="form-control"
                                           placeholder="دنبال چه دوره ای میگردی؟"
                                           type="text">
                                    <span class="input-group-btn">
												<button type="submit" class="btn"><i
                                                        class="fa fa-arrow-left"></i></button>
											</span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-5 col-md-7 col-sm-12">
                    <div class="row">
                        <div class="col-6 col-lg-6 col-md-6 col-sm-6">
                            <div class="widget footer_widget">
                                <h5 class="footer-title">دسترسی سریع</h5>
                                <ul>
                                    <li><a href="{% url 'index:index_page' %}">خانه</a></li>
                                    <li><a href="{% url 'course:course_list' %}">دوره‌ها</a></li>
                                    <li><a href="{% url 'about_us:about_us' %}">درباره ما</a></li>
                                    <li><a href="{% url 'contact:contact_create' %}">تماس با ما</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-6 col-lg-6 col-md-6 col-sm-6">
                            <div class="widget footer_widget">
                                <h5 class="footer-title">دوره‌ها</h5>
                                <ul>
                                    {% for category in categories %}
                                        <li>
                                            <a href="{% url 'course:course_list' %}?categories={{ category.title }}">{{ category.title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-3 col-md-5 col-sm-12 footer-col-4">
                    <div class="widget widget_gallery gallery-grid-4">
                        <h5 class="footer-title">مقالات</h5>
                        <ul class="magnific-image">
                            {% for blog in blogs %}
                                <li><a href="{% url 'blog:blog_detail' blog.pk blog.slug %}"
                                       class="magnific-anchor"><img
                                        src="{{ blog.image.url }}" alt="{{ blog.title }}"></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 text-center"> © 1400 <span
                        class="text-white">{{ site_title }}</span> تمامی حقوق محفوظ است
                </div>
            </div>
        </div>
    </div>
</footer>

templates/Shared/Header.html
{% load static %}
<header class="header rs-nav">
    <div class="top-bar">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="topbar-left">
                    <ul>
                        <li><a href="{% url 'contact:contact_create' %}"><i class="fa fa-phone"></i>تماس با ما</a></li>
                        <li><a href="mailto:{{ email }}"><i class="fa fa-envelope-o"></i>{{ email }}</a></li>
                    </ul>
                </div>
                <div class="topbar-right">
                    <ul>
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'account:register' %}">ثبت ‌نام</a></li>
                            <li><a href="{% url 'account:login' %}">ورود</a></li>
                        {% else %}
                            <li><a>{{ user.fullname_or_username }}</a></li>
                            <li><a href="{% url 'account:profile' %}">حساب کاربری</a></li>
                            <li><a href="{% url 'account:logout' %}?next={{ request.get_full_path }}">خروج</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="sticky-header navbar-expand-lg">
        <div class="menu-bar clearfix">
            <div class="container clearfix">
                <!-- Header Logo ==== -->
                <div class="menu-logo">
                    <a href="{% url 'index:index_page' %}"><img src="{% static 'images/logo.png' %}" alt=""></a>
                </div>
                <!-- Mobile Nav Button ==== -->
                <button class="navbar-toggler collapsed menuicon justify-content-end" type="button"
                        data-toggle="collapse"
                        data-target="#menuDropdown" aria-controls="menuDropdown" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <!-- Author Nav ==== -->
                <div class="secondary-menu">
                    <div class="secondary-inner">
                        <ul>
                            {% if youtube %}
                            <li><a target="_blank" href="{{ youtube }}" class="btn-link"><i
                                    class="fa fa-youtube-play"></i></a></li>
                            {% endif %}
                            {% if twitter %}        
                            <li><a target="_blank" href="https://twitter.com/{{ twitter }}" class="btn-link"><i
                                    class="fa fa-twitter"></i></a></li>
                            {% endif %}
                            {% if instagram %}        
                            <li><a target="_blank" href="https://www.instagram.com/{{ instagram }}" class="btn-link"><i
                                    class="fa fa-instagram"></i></a></li>
                            {% endif %}        
                            <!-- Search Button ==== -->
                            <li class="search-btn">
                                <button id="quik-search-btn" type="button" class="btn-link"><i
                                        class="fa fa-search"></i></button>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Search Box ==== -->
                <div class="nav-search-bar">
                    <form method="get" action="{% url 'course:course_list' %}">
                        <input name="search" value="" type="text" class="form-control" placeholder="جستجو دوره ...">
                        <span><button type="submit" style="background: none;border: none"><i
                                class="ti-search"></i></button></span>
                    </form>
                    <span id="search-remove"><i class="ti-close"></i></span>
                </div>
                <!-- Navigation Menu ==== -->
                <div class="menu-links navbar-collapse collapse justify-content-start" id="menuDropdown">
                    <div class="menu-logo">
                        <a href="index.html"><img src="assets/images/logo.png" alt=""></a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'index:index_page' %}">صفحه اصلی</a>
                        </li>
                        <li><a href="javascript:;">دوره ها <i class="fa fa-chevron-down"></i></a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="{% url 'course:course_list' %}">همه دوره ها</a>
                                </li>
                                {% for category in categories %}
                                    <li>
                                        <a href="{{ category.category_url }}">{{ category.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="{% url 'blog:blog_list' %}">مقالات</a>
                        <li><a href="{% url 'contact:contact_create' %}" >تماس با ما</a></li>
                        <li><a href="{% url 'about_us:about_us' %}" >درباره ما</a></li>
                    </ul>
                </div>
                <!-- Navigation Menu END ==== -->
            </div>
        </div>
    </div>
</header>

templates/Shared/_FooterReferences.html
{% load static %}
<!-- External JavaScripts -->
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "vendors/bootstrap/js/popper.min.js" %}"></script>
<script src="{% static "vendors/bootstrap/js/bootstrap.min.js" %}"></script>
<script src="{% static "vendors/bootstrap-select/bootstrap-select.min.js" %}"></script>
<script src="{% static "vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js" %}"></script>
<script src="{% static "vendors/magnific-popup/magnific-popup.js" %}"></script>
<script src="{% static "vendors/counter/waypoints-min.js" %}"></script>
<script src="{% static "vendors/counter/counterup.min.js" %}"></script>
<script src="{% static "vendors/imagesloaded/imagesloaded.js" %}"></script>
<script src="{% static "vendors/masonry/masonry.js" %}"></script>
<script src="{% static "vendors/masonry/filter.js" %}"></script>
<script src="{% static "vendors/owl-carousel/owl.carousel.js" %}"></script>
<script src="{% static "js/jquery.scroller.js" %}"></script>
<script src="{% static "js/functions.js" %}"></script>
<script src="{% static "js/contact.js" %}"></script>
<script src="{% static "vendors/switcher/switcher.js" %}"></script>

templates/Shared/_HeaderReferences.html
{% load static %}
<!-- META ============================================= -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="canonical" href="index-2.html"/>
<!-- OG -->
<meta name="robots" content="index, follow">

<meta name="keywords" content="Web Design, Education, Institute, Study"/>
<meta name="author" content="ThemeTrades"/>
<meta name="description"
      content="EduChamp is a Fully Creative Mobile Responsive HTML Template. It is designed specifically for University, College, School, Training centre or other educational institute."/>

<meta property="og:url" content="index-2.html"/>
<meta property="og:site_name" content="EduChamp : Education HTML Template"/>
<meta property="og:type" content="website"/>
<meta property="og:locale" content="en_us"/>
<meta property="og:title" content="EduChamp : Education HTML Template"/>
<meta property="og:description"
      content="EduChamp is a Fully Creative Mobile Responsive HTML Template. It is designed specifically for University, College, School, Training center or other educational institute."/>
<meta property="og:image" content="preview.png"/>

<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="index-2.html">
<meta name="twitter:creator" content="@themetrades">
<meta name="twitter:title" content="EduChamp : Education HTML Template">
<meta name="twitter:description"
      content="EduChamp is a Fully Creative Mobile Responsive HTML Template. It is designed specifically for University, College, School, Training centre or other educational institute.">

<meta name="format-detection" content="telephone=no">

<!-- FAVICONS ICON ============================================= -->
<link rel="icon" href="{{ icon }}" type="image/x-icon"/>


<!-- MOBILE SPECIFIC ============================================= -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.min.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

<!-- All PLUGINS CSS ============================================= -->
<link rel="stylesheet" type="text/css" href="{% static "css/assets.css" %}">

<!-- TYPOGRAPHY ============================================= -->
<link rel="stylesheet" type="text/css" href="{% static "css/typography.css" %}">

<!-- SHORTCODES ============================================= -->
<link rel="stylesheet" type="text/css" href="{% static "css/shortcodes/shortcodes.css" %}">

<!-- STYLESHEETS ============================================= -->
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
<link class="skin" rel="stylesheet" type="text/css" href="{% static "css/color/color-1.css" %}">