account_app/urls.py
from django.urls import path
from .views import (
    Register, Login, logout_view, add_course_to_cart, CartView, delete_course_from_cart, MyCourses,
    PasswordChange, CourseAdd, TeacherCourses, MyComment, TeacherBlogs, PaymentList, PaymentDetail, BlogCreate,VideoAdd,VideoUpdate
    ,PasswordReset,PasswordResetConfirm,ProfileUpdate,BlogUpdate,CourseUpdate,VideoList,checkout,apply_coupon_code,remove_coupon_code
)

app_name = 'account'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('apply-coupon-code/', apply_coupon_code, name='apply_coupon_code'),
    path('remove-coupon-code/', remove_coupon_code, name='remove_coupon_code'),
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password_change'),
    path('profile/', ProfileUpdate.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
    path('my-courses/', MyCourses.as_view(), name='my_courses'),
    path('add-courses-to-order/<int:pk>/', add_course_to_cart, name='add_course_to_cart'),
    path('delete-courses-from-order/<int:pk>/', delete_course_from_cart, name='delete_course_to_cart'),
    path('course-add/', CourseAdd.as_view(), name='course_add'),
    path('course-update/<int:pk>/', CourseUpdate.as_view(), name='course_update'),
    path('teacher-videos-courses/', VideoList.as_view(), name='teacher_videos'),
    path('video-course-add/', VideoAdd.as_view(), name='video_course_add'),
    path('video-course-update/<int:pk>/', VideoUpdate.as_view(), name='video_course_update'),
    path('teacher-courses/', TeacherCourses.as_view(), name='teacher_courses'),
    path('my-comment/', MyComment.as_view(), name='my_comment'),
    path('teacher-blogs/', TeacherBlogs.as_view(), name='teacher_blogs'),
    path('blog-create/', BlogCreate.as_view(), name='blog_create'),
    path('blog-update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('payments/', PaymentList.as_view(), name='payment_list'),
    path('payments/<int:pk>/', PaymentDetail.as_view(), name='payment_detail'),
    path('password-reset/',PasswordReset.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload
from azbankgateways.urls import az_bank_gateways_urls
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('index_app.urls', namespace='index')),
    path('', include('course_app.urls', namespace='course')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('order_app.urls', namespace='order')),
    path('', include('blog_app.urls', namespace='blog')),
    path('contact/', include('contact_app.urls', namespace='contact')),
    path('account/', include('account_app.urls', namespace='account')),
    path('about-us/',include('about_app.urls',namespace='about_us')),
    path('editor/uploads/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/login/', RedirectView.as_view(url='/account/login/')),
    path('admin/', admin.site.urls),
]

handler404 = 'config.views.view_404'
handler403 = 'config.views.view_403'
handler400 = 'config.views.view_400'
handler500 = 'config.views.view_500'

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/payment/payment-failed.html
{% extends 'account/AccountBase.html' %}
{% load widget_tweaks %}
{% load humanize %}
{% block head_title %}نتیجه پرداخت{% endblock %}
{% block page_title %}
<li>نتیجه پرداخت</li>{% endblock %}
{% block content %}
<div class="row">
    <!-- Your Profile Views Chart -->
    <div class="col-lg-12 m-b30">
        <div class="widget-box">
            <div class="wc-title">
                <h4>پرداخت ناموفق بود</h4>
            </div>
            <div class="widget-inner">
                <div class="col-12 text-center">
                    <i class="fa fa-times-circle text-danger mb-3" style="font-size:10rem"></i>
                    <p class="alert alert-danger text-center" style="font-family: iransans-light;font-size:18px">پرداخت
                        ناموفق بود. اگر پول کم شده است ظرف مدت ۴۸ ساعت پول به حساب شما بازخواهد گشت</p>
                    <div class="badge badge-warning p-2 mt-2">
                        <a style="color:#2b2b2b" href="{% url 'account:cart' %}">بازگشت به سبد خرید</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Your Profile Views Chart END-->
    </div>
</div>
{% endblock %}

templates/payment/payment-success.html
{% extends 'account/AccountBase.html' %}
{% load widget_tweaks %}
{% load humanize %}
{% block head_title %}نتیجه پرداخت{% endblock %}
{% block page_title %}
<li>نتیجه پرداخت</li>{% endblock %}
{% block content %}
<div class="row">
    <!-- Your Profile Views Chart -->
    <div class="col-lg-12 m-b30">
        <div class="widget-box">
            <div class="wc-title">
                <h4>تایید پرداخت</h4>
            </div>
            <div class="widget-inner">
                <div class="col-12 text-center">
                    <i class="fa fa-check-circle text-success mb-3" style="font-size:10rem"></i>
                    <p class="alert alert-success text-center" style="font-family: iransans-light;font-size:18px">پرداخت
                        با موفقیت انجام شد. شناسه خرید {{ order_id }} #</p>
                    <div class="badge badge-info p-2 mt-2">
                        <a style="padding:0 10px;color:#2b2b2b" href="{% url 'account:payment_detail' order_id %}">مشاهده سفارش</a>
                        <a style="padding:0 10px;color:#2b2b2b" href="{% url 'account:my_courses' %}">دوره های من</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Your Profile Views Chart END-->
    </div>
</div>
{% endblock %}